name: Manual dev rebuild
on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
jobs:
  rebuild-env-manually:
    name: Rebuild dev env manually
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Connect to server and update docker
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.port || 22 }}
          script: |
            cd ~/workspace/infrastructure/docker/${{ inputs.environment }}
            docker compose pull
            docker compose up -d --build
            docker image prune -f
