name: Manual env rebuild
run-name: Manual Rebuild for ${{ inputs.environment }} triggered by @${{ github.actor }}
on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, staging, prod)'
        type: choice
        options:
          - dev
          - prod
        required: true
        default: 'dev'
jobs:
  rebuild-env-manually:
    name: Rebuild env manually
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create .env file on runner
        run: |
          echo "Creating .env file for ${{ inputs.environment }} environment..."
          # Use GitHub Actions expressions directly to populate the .env file.
          # This removes the need for a separate 'env:' block.
          cat << EOF > .env
          BE_POSTGRES_DB=${{ vars.BE_POSTGRES_DB }}
          BE_POSTGRES_USER=${{ secrets.BE_POSTGRES_USER }}
          BE_POSTGRES_PASSWORD=${{ secrets.BE_POSTGRES_PASSWORD }}
          KC_POSTGRES_DB=${{ vars.KC_POSTGRES_DB }}
          KC_POSTGRES_USER=${{ secrets.KC_POSTGRES_USER }}
          KC_POSTGRES_PASSWORD=${{ secrets.KC_POSTGRES_PASSWORD }}
          KC_ADMIN=${{ secrets.KC_ADMIN }}
          KC_ADMIN_PASSWORD=${{ secrets.KC_ADMIN_PASSWORD }}
          DOMAIN=${{ vars.DOMAIN }}
          BACKEND_KEYCLOAK_CLIENT_ID=${{ vars.BACKEND_KEYCLOAK_CLIENT_ID }}
          BACKEND_KEYCLOAK_CLIENT_SECRET=${{ secrets.BACKEND_KEYCLOAK_CLIENT_SECRET }}
          FRONTEND_KEYCLOAK_CLIENT_ID=${{ vars.FRONTEND_KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_REALM=${{ vars.KEYCLOAK_REALM }}
          EOF

      - name: Copy .env file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ vars.SERVER_PORT || 22 }}
          source: ".env"
          target: "~/workspace/infrastructure/docker/${{ inputs.environment }}/"

      - name: Update repository and restart services on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ vars.SERVER_PORT || 22 }}
          script: |
            set -e
            cd ~/workspace/infrastructure
            echo "Pulling latest changes from repository..."
            git fetch origin main
            git reset --hard origin/main
            
            echo "Restarting services with new .env file..."
            cd ~/workspace/infrastructure/docker/${{ inputs.environment }}
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f
